declare const self: ServiceWorkerGlobalScope & { __WB_MANIFEST: Array<{ url: string; revision: string | null }> };

import { precacheAndRoute } from 'workbox-precaching';

// Precache all resources generated by the build process
precacheAndRoute(self.__WB_MANIFEST || []);

interface PushPayload {
  title?: string;
  body?: string;
  url?: string;
}

// Listen for push notifications
self.addEventListener('push', (event: PushEvent) => {
  try {
    let payload: PushPayload = {};
    if (event.data) {
      payload = event.data.json() as PushPayload;
    }
    
    const title = payload.title || 'Budgetizer 💰';
    const options: NotificationOptions = {
      body: payload.body || 'Mise à jour de votre compte.',
      icon: '/pwa-192x192.png',
      badge: '/favicon.svg',
      vibrate: [100, 50, 100],
      data: {
        url: payload.url || '/'
      }
    };
    
    event.waitUntil(
      self.registration.showNotification(title, options)
    );
  } catch (error) {
    console.error('Error handling push event:', error);
  }
});

// Listen for notification click events to navigate inside the app
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();
  
  // Resolve absolute URL
  const urlToOpen = new URL(event.notification.data?.url || '/', self.location.origin).href;
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients: readonly WindowClient[]) => {
      // If there's an open window matching the URL, focus it
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client && client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
